version: '3.8'

services:
  task-manager-svc:
    build: .
    container_name: task-manager
    ports:
      - "50051:50051"
    environment:
      DB_HOST: task-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: task_db
      NATS_URL: nats://nats:4222
    depends_on:
      - task-db
      - nats

  task-db:
    image: mysql:8.0
    container_name: task-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"

volumes:
  db_data: