version: '3.8'

services:
  task-manager-svc:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: task-manager
    ports:
      - "50051:50051"
    environment:
      DB_HOST: task-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: task_db
      NATS_URL: nats://nats:4222
    depends_on:
      - task-db
      - nats
      - log-aggregator-svc

  task-db:
    image: mysql:8.0
    container_name: task-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"

  log-aggregator-svc:
    build:
      context: ../../log-aggregator-svc
    container_name: log-aggregator
    environment:
      NATS_URL: nats://nats:4222
      MONGO_URL: mongodb://log-mongo:27017
      MONGO_DB: logdb
    depends_on:
      - log-mongo
      - nats
    ports:
      - "8080:8080"

  log-mongo:
    image: mongo:latest
    container_name: log-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - log_mongo_data:/data/db

volumes:
  db_data:
  log_mongo_data: